version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=flight-price-tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - app-network

  notification-service:
    image: gcerveira/flight-price-notification:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
